# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "proc-composer", path: "../../composer/ruby"

group :development do
  gem "dotenv"
  gem "standardrb"
end

group :test do
  gem "rspec"
end
