commit:
  changelogs:
    - label: "commit.changelog"
      destination: "./CHANGELOG.md"

  changetypes:
    - label: "commit.type.add"
      name: "add"
    - label: "commit.type.chg"
      name: "chg"
    - label: "commit.type.fix"
      name: "fix"
    - label: "commit.type.dep"
      name: "dep"

  includes:
    - git
    - base

  externals:
    - repo: "metabahn/commit-templates"
      private: true
